# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/l47/l47.xci
# IP: The module: 'l47' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/l47/l47_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'l47'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/l47/l47.xci
# IP: The module: 'l47' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/l47/l47_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'l47'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
