# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s25ftgb196-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/r52
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/l51
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/r45
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/l42
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/l41
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/wei2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/yanl
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/yanr
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/cheng2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/wan2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/shi2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/ce2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/shi_rom_1
  } {
      F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/r52
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/l51
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/r45
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/l42
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/l41
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/wei2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/yanl
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/yanr
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/cheng2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/wan2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/shi2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/ce2
    f:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/ip/shi_rom_1
  } {
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r52_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l51_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r45_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l42_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l41_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/wei2_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/yanl_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/yanr_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/cheng2_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/wan2_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/shi2_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/ce2_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/shi_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/kai_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/si_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/dan_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/yan_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/wan_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/cheng_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/ku_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/xiao_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/zheng_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/que_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/cuo_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/wu_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/clk_wiz_0_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/rgb2dvi_0_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r41_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/zuo_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/you_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/wei_rom_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r40_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l40_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r42_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r43_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l43_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l44_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r44_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l45_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l46_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r46_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r47_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l47_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r48_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l48_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r49_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l49_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r50_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l50_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r51_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l52_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/l53_stub.v
      F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/realtime/r53_stub.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/Driver_HDMI.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/HDMI_Demo.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/Result_Data.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/button.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/random_number.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/shili_control.v
      F:/Summer_xilinx/shiliyi/HDMI_Demo.srcs/sources_1/new/smg.v
    }
      rt::read_vhdl -lib xpm F:/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top smg
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "F:/Summer_xilinx/shiliyi/.Xil/Vivado-17680-DESKTOP-NJ34O24/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
