# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SEAEnglish/example2/HDMI_Demo/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/wu_rom/wu_rom.xci
# IP: The module: 'wu_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SEAEnglish/example2/HDMI_Demo/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/wu_rom/wu_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wu_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SEAEnglish/example2/HDMI_Demo/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/wu_rom/wu_rom.xci
# IP: The module: 'wu_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SEAEnglish/example2/HDMI_Demo/HDMI_Demo/HDMI_Demo.srcs/sources_1/ip/wu_rom/wu_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wu_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
