# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/si_rom/si_rom.xci
# IP: The module: 'si_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/si_rom/si_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'si_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/si_rom/si_rom.xci
# IP: The module: 'si_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Qzzzz/Desktop/shiliyi/shiliyi/HDMI_Demo.srcs/sources_1/ip/si_rom/si_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'si_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
