# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/r52/r52.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r52 || ORIG_REF_NAME==r52} -quiet] -quiet

# IP: ip/l51/l51.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==l51 || ORIG_REF_NAME==l51} -quiet] -quiet

# IP: ip/r45/r45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r45 || ORIG_REF_NAME==r45} -quiet] -quiet

# IP: ip/l42/l42.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==l42 || ORIG_REF_NAME==l42} -quiet] -quiet

# IP: ip/l41/l41.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==l41 || ORIG_REF_NAME==l41} -quiet] -quiet

# IP: ip/wei2/wei2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wei2 || ORIG_REF_NAME==wei2} -quiet] -quiet

# IP: ip/yanl/yanl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yanl || ORIG_REF_NAME==yanl} -quiet] -quiet

# IP: ip/yanr/yanr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==yanr || ORIG_REF_NAME==yanr} -quiet] -quiet

# IP: ip/cheng2/cheng2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cheng2 || ORIG_REF_NAME==cheng2} -quiet] -quiet

# IP: ip/wan2/wan2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wan2 || ORIG_REF_NAME==wan2} -quiet] -quiet

# IP: ip/shi2/shi2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==shi2 || ORIG_REF_NAME==shi2} -quiet] -quiet

# IP: ip/ce2/ce2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ce2 || ORIG_REF_NAME==ce2} -quiet] -quiet
