# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# IP: ip/Picture_B_Rom/Picture_B_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Picture_B_Rom || ORIG_REF_NAME==Picture_B_Rom} -quiet] -quiet

# IP: ip/Picture_G_Rom/Picture_G_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Picture_G_Rom || ORIG_REF_NAME==Picture_G_Rom} -quiet] -quiet

# IP: ip/Picture_R_Rom/Picture_R_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Picture_R_Rom || ORIG_REF_NAME==Picture_R_Rom} -quiet] -quiet
