# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sys.xdc

# IP: ip/r45/r45.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==r45 || ORIG_REF_NAME==r45} -quiet] -quiet
